export const LOAD_TWEETS = 'LOAD_TWEETS';
export const LOAD_TWEETS_SUCCESS = 'LOAD_TWEETS_SUCCESS';
export const LOAD_TWEETS_ERROR = 'LOAD_TWEETS_ERROR';
export const LOAD_MORE_TWEETS = 'LOAD_MORE_TWEETS';
export const LOAD_MORE_TWEETS_SUCCESS = 'LOAD_MORE_TWEETS_SUCCESS';
export const LOAD_MORE_TWEETS_ERROR = 'LOAD_MORE_TWEETS_ERROR';
